services:
  bitcoin-core:
    image: ruimarinho/bitcoin-core:latest
    ports:
      - "8332:8332" 
      - "8333:8333" 
    volumes:
      - ./bitcoin.conf:/home/bitcoin/.bitcoin/bitcoin.conf 
      - bitcoin-data:/home/bitcoin/.bitcoin 
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "bitcoin-cli -rpcuser=user1 -rpcpassword=123456 -rpcconnect=127.0.0.1 getblockchaininfo || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./rust_bitcoin
    ports:
      - "8080:8080"
      - "3030:3030"
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/block_chain
      - BITCOIN_RPC_URL=http://bitcoin-core:8332
      - BITCOIN_RPC_USER=user1
      - BITCOIN_RPC_PASS=123456
    depends_on:
      mysql:
        condition: service_healthy
      bitcoin-core:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://backend:3030/block_data || exit 1"]  
      interval: 10s  
      timeout: 5s    
      retries: 5     
      start_period: 60s  

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: block_chain
    ports:
      - "3307:3306"  
    networks:
      - app-network
    volumes:
      - mysql-data:/var/lib/mysql  # 数据持久化存储
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  frontend:
    build:
      context: ./vue_bitcoin_ts
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy  

volumes:
  bitcoin-data:
    name: bitcoin-data
  mysql-data:  
    name: mysql-data

networks:
  app-network:
    driver: bridge
