version: '3'
services:
  frontend:
    build:
      context: ./vue_bitcoin_ts
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      backend:
        condition: service_healthy  

  backend:
    build:
      context: ./rust_bitcoin
    ports:
      - "8080:8080"
      - "3030:3030"
    environment:
      - DATABASE_URL=mysql://root:MySQL000000.@mysql:3306/block_chain
      - BITCOIN_RPC_URL=http://bitcoin-core:8332
      - BITCOIN_RPC_USER=user1
      - BITCOIN_RPC_PASS=123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3030/block_data || exit 1"]  
      interval: 10s  
      timeout: 5s    
      retries: 5     
      start_period: 60s  

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: MySQL000000.
      MYSQL_DATABASE: block_chain
    ports:
      - "3307:3306"  
    networks:
      - app-network
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
