name: Deploy to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create Temporary Key File
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
        
    - name: Test SSH Key
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} echo "SSH connected successfully"
    - name: Debug Private Key
      run: |
        echo "${{ secrets.EC2_KEY }}" | sed 's/^/DEBUG: /'

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}      # Fetch the host address from Secrets
        username: ${{ secrets.EC2_USER }} # Fetch the username from Secrets
        key: ${{ secrets.EC2_KEY }}             # Use the temporary key file
        options: "-o StrictHostKeyChecking=no"
        port: 22
        script: |
          echo "Connecting to EC2 instance ${EC2_HOST}..."
          ssh-add -l  # 检查加载的密钥
          ls -la ~/.ssh  # 确认 .ssh 目录的内容和权限
          cat ~/.ssh/authorized_keys  # 确认公钥文件是否正确
          # Install necessary packages
          sudo apt update
          sudo apt install snapd -y
          sudo apt install git -y
          sudo snap install docker
          sudo snap start docker
          sudo groupadd docker
          sudo usermod -aG docker $USER
          newgrp docker
          sudo chown root:docker /var/run/docker.sock
          
          git clone https://github.com/Peilin-zzz-Eric/bitcoin_project.git || (cd bitcoin_project && git pull)
          cd bitcoin_project
          docker-compose build --no-cache
          docker-compose up -d


    - name: Delete Temporary Key File
      run: rm -f ec2_key.pem
          
